baseurl = "https://fsnotify.org/"
languageCode = "en-us"
title = "fsnotify"
theme = "hyde"

[permalinks]
post = "/:filename/"

[Params]
description = "File system notifications for Go."

[[menu.main]]
name = "Source Code"
url = "https://github.com/fsnotify/fsnotify"

[[menu.main]]
name = "Documentation"
url = "https://pkg.go.dev/github.com/fsnotify/fsnotify"

[deployment]
order = [".png$", ".jpg$", ".gif$", ".svg$"]

[[deployment.targets]]
URL = "s3://fsnotify.org?region=ca-central-1"

[[deployment.matchers]]
# Cache static assets for 20 years.
pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
